apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ default "default" .Release.Namespace }}
spec:
  replicas: {{ default 1 .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-api
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-api
    spec:
      containers:
        - name: {{ .Values.name }}-api
          image: maratonaaksacr.azurecr.io/porto-backend:{{ .Values.image.tag }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          ports:
            - containerPort: {{ default 3000 .Values.appPort }}
              name: http
          env:
            - name: DATABASE_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secret
                  key: database_mongodb_uri
            - name: DATABASE_MONGODB_DBNAME
              value: {{ default "ship_manager" .Values.deployment.envs.dbName }}
