apiVersion: v1
kind: Secret
metadata:
  name: {{ default "porto-backend-secret" .Values.secret.name }}
type: Opaque
stringData:
  database_mongodb_uri: {{ required "Db URI is mandatory!" .Values.secret.mongodb_uri }}