apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  selector:
    app: {{ .Values.name }}-api
  ports:
  - name: http
    port: {{ default 80 .Values.service.port }}
    targetPort: http