name: porto-backend
image:
  tag: v1.0.0
appPort: 3000

deployment:
  envs:
    dbName: ship_manager
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

ingress:
  hostName: porto-backend-api.add1d436085848758dc8.eastus.aksapp.io

secret:
  name:
  mongodb_uri:

service:
  port: